CREATE OR REPLACE VIEW {bq_project}.{legacy_dataset}.final_change_history AS
SELECT
    Day,
    account_name AS AccountName,
    "" AS CID,
    account_id,
    Currency,
    campaign_sub_type AS CampaignSubType,
    campaign_name AS CampaignName,
    campaign_id AS CampaignID,
    app_store AS Store,
    app_id AS AppId,
    campaign_status AS CampaignStatus,
    bidding_strategy AS UACType,
    start_date AS StartDate,
    FALSE AS VideoModeOnly,
    -- firebase_bidding_status,
    target_conversions AS TargetConversions,
    geos AS country_code,
    languages AS Language,
    REGEXP_CONTAINS(languages, r"en|All") AS English,
    n_of_target_conversions,
    "" AS cannibalization_hash_strict,
    "" AS cannibalization_hash_medium,
    "" AS cannibalization_hash_flex,
    "" AS cannibalization_hash_broad,
    days_since_start_date AS Ndays,
    current_budget_amount AS CurrentBudget,
    target_cpa AS targetCPA,
    current_target_cpa AS currentTargetCPA,
    current_target_cpa AS LastTCPA,
    current_target_cpa AS CurrentTCPA,
    target_roas AS targetROAS,
    current_target_roas AS currentTROAS,
    budget AS Budget,
    bid_changes AS BidChanges,
    budget_changes AS BudgetChanges,
    clicks,
    impressions,
    cost,
    installs,
    installs_adjusted,
    inapps,
    inapps_adjusted,
    conversions_value AS conversion_value,
    conversions,
    conversions_adjusted,
    is_budget_limited AS Limited,
    is_budget_overshooting AS Overshooting,
    is_budget_underspend AS Underspend,
    is_cpa_overshooting AS CPAOvershooting,
    geo_changes AS GeoChanges,
    image_changes AS ImageChanges,
    text_changes AS TextChanges,
    html5_changes AS HTML5Changes,
    video_changes AS VideoChanges,
    0 AS ad_groups_added,
    0 AS ad_groups_resumed,
    0 AS ad_groups_paused,
    0 AS ad_groups_deleted,
    SAFE_DIVIDE(cost, conversions) AS CPA
FROM {bq_project}.{target_dataset}.final_change_history;
