CREATE OR REPLACE VIEW {legacy_dataset}.uacassets_all_conversion_split AS
WITH AssetMapping AS (
  SELECT
    FORMAT_DATE("%F", Day) AS Day,
    AccountName,
    account_id,
    CID,
    CampaignSubType,
    Store,
    AppId,
    CAST(AdGroupId AS STRING) AS AdGroupId,
    AdGroup AS AdGroupName,
    AdGroupStatus,
    CampaignName,
    CampaignID,
    CampaignStatus,
    UACType,
    TargetConversions,
    Currency,
    country_code,
    Language,
    English,
    AssetType,
    AdAsset,
    FeedDataOriginal,
    FeedData,
    PerformanceGrouping,
    mediaid,
    sourceUrl,
    mediafilesize,
    LinkToCampaign,
    ImageSize,
    VideoOrientation,
    video_aspect_ratio,
    video_length_bucket,
    RecommendedImage,
    ImageSizeType,
    RefinedImageSize,
    Link,
    CreationTime,
    Status,
    firebase_bidding_status,
    Network,
    SUM(cost) AS cost
  FROM
    {legacy_dataset}.uacassets
  GROUP BY
    Day,
    AccountName,
    account_id,
    CID,
    CampaignSubType,
    Store,
    AppId,
    AdGroupId,
    AdGroupName,
    AdGroupStatus,
    CampaignName,
    CampaignID,
    CampaignStatus,
    UACType,
    TargetConversions,
    Currency,
    country_code,
    Language,
    English,
    AssetType,
    AdAsset,
    FeedDataOriginal,
    FeedData,
    PerformanceGrouping,
    mediaid,
    sourceUrl,
    mediafilesize,
    LinkToCampaign,
    ImageSize,
    VideoOrientation,
    video_aspect_ratio,
    video_length_bucket,
    RecommendedImage,
    ImageSizeType,
    RefinedImageSize,
    Link,
    CreationTime,
    Status,
    Network,
    firebase_bidding_status
  ),
  ConversionSplitFormatted AS (
    SELECT
      date AS Day,
      CAST(ad_group_id AS STRING) AS AdGroupId,
      asset_id AS FeedDataOriginal,
      {bq_dataset}.ConvertAdNetwork(Network)  Network,
      CASE conversion_type
        WHEN "DOWNLOAD" THEN "Download"
        WHEN "PURCHASE" THEN "Purchase"
        WHEN "PAGE_VIEW" THEN "Page View"
        ELSE "Other"
        END AS conversion_category,
      conversion_name,
      all_conversions,
      all_conversions_value,
      conversions_value,
      view_through_conversions
    FROM
      {bq_dataset}.asset_conversion_split
    JOIN
      {bq_dataset}.app_conversions_mapping cmap
      USING(conversion_id)
    )
SELECT
  Day,
  AccountName,
  account_id,
  CID,
  CampaignSubType,
  Store,
  AppId,
  AdGroupId,
  AdGroupName,
  AdGroupStatus,
  CampaignName,
  CampaignID,
  CampaignStatus,
  UACType,
  TargetConversions,
  Currency,
  country_code,
  Language,
  English,
  AssetType,
  AdAsset,
  FeedDataOriginal,
  FeedData,
  PerformanceGrouping,
  mediaid,
  sourceUrl,
  mediafilesize,
  LinkToCampaign,
  ImageSize,
  VideoOrientation,
  video_aspect_ratio,
  video_length_bucket,
  RecommendedImage,
  ImageSizeType,
  RefinedImageSize,
  Link,
  CreationTime,
  Status,
  Network,
  firebase_bidding_status,
  conversion_category,
  conversion_name,
  MIN(cost) AS cost,
  MIN(all_conversions) AS all_conversions,
  MIN(all_conversions_value) AS all_conversion_value,
  MIN(conversions_value) AS conversions_value,
  MIN(view_through_conversions) AS view_through_conversions
FROM
  ConversionSplitFormatted
LEFT JOIN AssetMapping
  USING(Day, Network, AdGroupId, FeedDataOriginal)
GROUP BY
  Day,
  AccountName,
  account_id,
  CID,
  CampaignSubType,
  Store,
  AppId,
  AdGroupId,
  AdGroupName,
  AdGroupStatus,
  CampaignName,
  CampaignID,
  CampaignStatus,
  UACType,
  TargetConversions,
  Currency,
  country_code,
  Language,
  English,
  AssetType,
  AdAsset,
  FeedDataOriginal,
  FeedData,
  PerformanceGrouping,
  mediaid,
  sourceUrl,
  mediafilesize,
  LinkToCampaign,
  ImageSize,
  VideoOrientation,
  video_aspect_ratio,
  video_length_bucket,
  RecommendedImage,
  ImageSizeType,
  RefinedImageSize,
  Link,
  CreationTime,
  Status,
  Network,
  firebase_bidding_status,
  conversion_category,
  conversion_name
