https://datastudio.google.com/c/reporting/create?c.mode=edit&c.reportId=187f1f41-16bc-434d-8437-7988bed6e8b9&
r.reportName=app_reporting_pack_copy&
ds.*.refreshFields=false&
ds.excellence.connector=bigQuery&
ds.excellence.datasourceName=creative_excellence_copy&
ds.excellence.projectId=YOUR_PROJECT_ID&
ds.excellence.type=TABLE&
ds.excellence.datasetId=YOUR_DATASET_ID&
ds.excellence.tableId=creative_excellence&

ds.assets.connector=bigQuery&
ds.assets.datasourceName=asset_performance_copy&
ds.assets.projectId=YOUR_PROJECT_ID&
ds.assets.type=TABLE&
ds.assets.datasetId=YOUR_DATASET_ID&
ds.assets.tableId=asset_performance&

ds.perf_group.connector=bigQuery&
ds.perf_group.datasourceName=performance_grouping_copy&
ds.perf_group.projectId=YOUR_PROJECT_ID&
ds.perf_group.type=TABLE&
ds.perf_group.datasetId=YOUR_DATASET_ID&
ds.perf_group.tableId=performance_grouping&

ds.network.connector=bigQuery&
ds.network.datasourceName=ad_group_network_split_copy&
ds.network.projectId=YOUR_PROJECT_ID&
ds.network.type=TABLE&
ds.network.datasetId=YOUR_DATASET_ID&
ds.network.tableId=ad_group_network_split&

ds.changes.connector=bigQuery&
ds.changes.datasourceName=change_history_copy&
ds.changes.projectId=YOUR_PROJECT_ID&
ds.changes.type=TABLE&
ds.changes.datasetId=YOUR_DATASET_ID&
ds.changes.tableId=change_history&

ds.approvals.connector=bigQuery&
ds.approvals.datasourceName=approval_statuses_copy&
ds.approvals.projectId=YOUR_PROJECT_ID&
ds.approvals.type=TABLE&
ds.approvals.datasetId=YOUR_DATASET_ID&
ds.approvals.tableId=approval_statuses
